export type AnimatecssAnimation =
  'animatecss_bounce' |
  'animatecss_flash' |
  'animatecss_pulse' |
  'animatecss_rubberBand' |
  'animatecss_shakeX' |
  'animatecss_shakeY' |
  'animatecss_headShake' |
  'animatecss_swing' |
  'animatecss_tada' |
  'animatecss_wobble' |
  'animatecss_jello' |
  'animatecss_heartBeat' |
  'animatecss_backInDown' |
  'animatecss_backInLeft' |
  'animatecss_backInRight' |
  'animatecss_backInUp' |
  'animatecss_backOutDown' |
  'animatecss_backOutLeft' |
  'animatecss_backOutRight' |
  'animatecss_backOutUp' |
  'animatecss_bounceIn' |
  'animatecss_bounceInDown' |
  'animatecss_bounceInLeft' |
  'animatecss_bounceInRight' |
  'animatecss_bounceInUp' |
  'animatecss_bounceOut' |
  'animatecss_bounceOutDown' |
  'animatecss_bounceOutLeft' |
  'animatecss_bounceOutRight' |
  'animatecss_bounceOutUp' |
  'animatecss_fadeIn' |
  'animatecss_fadeInDown' |
  'animatecss_fadeInDownBig' |
  'animatecss_fadeInLeft' |
  'animatecss_fadeInLeftBig' |
  'animatecss_fadeInRight' |
  'animatecss_fadeInRightBig' |
  'animatecss_fadeInUp' |
  'animatecss_fadeInUpBig' |
  'animatecss_fadeOut' |
  'animatecss_fadeOutDown' |
  'animatecss_fadeOutDownBig' |
  'animatecss_fadeOutLeft' |
  'animatecss_fadeOutLeftBig' |
  'animatecss_fadeOutRight' |
  'animatecss_fadeOutRightBig' |
  'animatecss_fadeOutUp' |
  'animatecss_fadeOutUpBig' |
  'animatecss_flipInX' |
  'animatecss_flipInY' |
  'animatecss_flipOutX' |
  'animatecss_flipOutY' |
  'animatecss_lightSpeedInRight' |
  'animatecss_lightSpeedInLeft' |
  'animatecss_lightSpeedOutRight' |
  'animatecss_lightSpeedOutLeft' |
  'animatecss_rotateIn' |
  'animatecss_rotateInDownLeft' |
  'animatecss_rotateInDownRight' |
  'animatecss_rotateInUpLeft' |
  'animatecss_rotateInUpRight' |
  'animatecss_rotateOut' |
  'animatecss_rotateOutDownLeft' |
  'animatecss_rotateOutDownRight' |
  'animatecss_rotateOutUpLeft' |
  'animatecss_rotateOutUpRight' |
  'animatecss_hinge' |
  'animatecss_jackInTheBox' |
  'animatecss_rollIn' |
  'animatecss_rollOut' |
  'animatecss_zoomIn' |
  'animatecss_zoomInDown' |
  'animatecss_zoomInLeft' |
  'animatecss_zoomInRight' |
  'animatecss_zoomInUp' |
  'animatecss_zoomOut' |
  'animatecss_zoomOutDown' |
  'animatecss_zoomOutLeft' |
  'animatecss_zoomOutRight' |
  'animatecss_zoomOutUp' |
  'animatecss_slideInDown' |
  'animatecss_slideInLeft' |
  'animatecss_slideInRight' |
  'animatecss_slideInUp' |
  'animatecss_slideOutDown' |
  'animatecss_slideOutLeft' |
  'animatecss_slideOutRight' |
  'animatecss_slideOutUp'
