export type MagiccssAnimation =
  'magiccss_magic' |
  'magiccss_twisterInDown' |
  'magiccss_twisterInUp' |
  'magiccss_swap' |
  'magiccss_puffIn' |
  'magiccss_puffOut' |
  'magiccss_vanishIn' |
  'magiccss_vanishOut' |
  'magiccss_openDownLeft' |
  'magiccss_openDownRight' |
  'magiccss_openUpLeft' |
  'magiccss_openUpRight' |
  'magiccss_openDownLeftReturn' |
  'magiccss_openDownRightReturn' |
  'magiccss_openUpLeftReturn' |
  'magiccss_openUpRightReturn' |
  'magiccss_openDownLeftOut' |
  'magiccss_openDownRightOut' |
  'magiccss_openUpLeftOut' |
  'magiccss_openUpRightOut' |
  'magiccss_perspectiveDown' |
  'magiccss_perspectiveUp' |
  'magiccss_perspectiveLeft' |
  'magiccss_perspectiveRight' |
  'magiccss_perspectiveDownReturn' |
  'magiccss_perspectiveUpReturn' |
  'magiccss_perspectiveLeftReturn' |
  'magiccss_perspectiveRightReturn' |
  'magiccss_rotateDown' |
  'magiccss_rotateUp' |
  'magiccss_rotateLeft' |
  'magiccss_rotateRight' |
  'magiccss_slideDown' |
  'magiccss_slideUp' |
  'magiccss_slideLeft' |
  'magiccss_slideRight' |
  'magiccss_rotateDownReturn' |
  'magiccss_rotateUpReturn' |
  'magiccss_rotateLeftReturn' |
  'magiccss_rotateRightReturn' |
  'magiccss_swashOut' |
  'magiccss_swashIn' |
  'magiccss_foolishIn' |
  'magiccss_holeOut' |
  'magiccss_tinLeftIn' |
  'magiccss_tinRightIn' |
  'magiccss_tinUpIn' |
  'magiccss_tinDownIn' |
  'magiccss_tinLeftOut' |
  'magiccss_tinRightOut' |
  'magiccss_tinUpOut' |
  'magiccss_tinDownOut' |
  'magiccss_bombLeftOut' |
  'magiccss_bombRightOut' |
  'magiccss_boingInUp' |
  'magiccss_boingOutDown' |
  'magiccss_spaceOutUp' |
  'magiccss_spaceOutRight' |
  'magiccss_spaceOutLeft' |
  'magiccss_spaceOutDown' |
  'magiccss_spaceInUp' |
  'magiccss_spaceInRight' |
  'magiccss_spaceInLeft' |
  'magiccss_spaceInDown'
