name: Publish to NPM

on:
  push:
    branches:
      - main  # Adjust branch name as necessary

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Check if version has changed
        id: version-check
        run: |
          VERSION=$(node -p "require('./package.json').version")
          NPM_VERSION=$(npm show @donerui/core version 2>/dev/null || echo "0.0.0")
          if [ "$VERSION" != "$NPM_VERSION" ]; then
            echo "VERSION_CHANGED=true" >> $GITHUB_ENV
          else
            echo "VERSION_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: build if version has changed
        if: steps.version-check.outputs.VERSION_CHANGED == 'true'
        run: npm run build

      - name: Publish to npm
        if: env.VERSION_CHANGED == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
